# no-clown-fiesta (light)
# [colors.primary]
# background = "0xe1e1e1"
# foreground = "0x151515"
#
# [colors.cursor]
# text = "0xd0d0d0"
# cursor = "0x151515"
#
# [colors.selection]
# text = "0x151515"
# background = "0xcfcfcf"
#
# [colors.normal]
# black = "0x151515"
# red = "0x874e42"
# green = "0x677940"
# yellow = "0xb89058"
# blue = "0x8ba1bf"
# magenta = "0xaa759f"
# cyan = "0x3e5f66"
# white = "0x373737"
#
# [colors.bright]
# black = "0xaaaaaa"
# red = "0x984936"
# green = "0x586935"
# yellow = "0xab8550"
# blue = "0x57788d"
# magenta = "0xaa749f"
# cyan = "0x51657b"
# white = "0x151515"

# no-clown-fiesta (dark)
[colors.primary]
background = "0x151515"
foreground = "0xe1e1e1"

[colors.cursor]
text = "0x151515"
cursor = "0xd0d0d0"

[colors.selection]
text = "0xe1e1e1"
background = "0x202020"

[colors.normal]
black = "0x151515"
red = "0xb46958"
green = "0x90a959"
yellow = "0xf4bf75"
blue = "0xbad7ff"
magenta = "0xaa759f"
cyan = "0x88afa2"
white = "0xafafaf"

[colors.bright]
black = "0x727272"
red = "0x984936"
green = "0x586935"
yellow = "0xab8550"
blue = "0xa2b5c1"
magenta = "0xaa749f"
cyan = "0x51657b"
white = "0xe1e1e1"

[env]
TERM = "xterm-256color"

[window]
opacity = 1

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
